---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Adding Vlan {{ ucsm_ip }}
    ucs_vlan:
      ip={{ucsm_ip}}
      login={{ucsm_login}}
      password={{ucsm_pw}}
      vlan_name='vlan_'
      vlan_id='10'
      mcast_policy_name=''
      policy_owner='local'

