---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Add Single VLAN Seperate FI A/B {{ ucsm_ip }}
    ucs_vlan:
      ip={{ucsm_ip}}
      login={{ucsm_login}}
      password={{ucsm_pw}}
      vlan_name="vlan_"
      mcast_policy_name="default"
      policy_owner="local"
      configure_lan_seperate='yes'
      vlan_a='199'
      vlan_b='299'

